### ISSUE TITLE
Update communication related to QRep token

### ISSUE THREAD

**Issue by antho1404** [0xkobe/quiver-website#14]
In the investor section, the benefits talk about getting QRep token, but this might be partially true as users **can** get airdrop of QRep but not guaranteed.

This issue has been raised here https://github.com/Quiver-Protocol/emotional-nft-dapp/issues/1#issuecomment-843011654

**Comment by EmmanuelDrouin** [comment]
@gopherquiv this issue has been created 14 days ago and hasn't been done since.
Who will handle the modification?

This is a priority as it's misleading early "investors" into what they gonna get ;)

Example: 
1- Users see the website
2- Users think they will have an NFT + QREP token + QSTK token
3- Users see the DApp without mention of the QREP token
4- Users start to question the project (how will I have my QREP? Will I have QREP anyway? etc.)

**We need to remove this part right now from the website**, as we talked about it already, cause there is no guarantee of getting QREP for NFT investors.

**Comment by gopherquiv** [comment]
Ok, we will organize QREP distribution session after DAO setup with NFT owners.

**Comment by EmmanuelDrouin** [comment]
If it's 100% sure that every NFT owner will receive the QREP tokens, you can just update the content on the QREP block to explain that, like "every NFT owners will be eligible to an upcoming QREP airdrop, more details coming soon" ;)

**Comment by gopherquiv** [comment]
Ok will do it

**Comment by EmmanuelDrouin** [comment]
@antho1404 @gopherquiv This issue has still not been resolve. 
It has been created 17 days ago and I Relaunched the discussion 3 days ago and still nothing.

Please do something here, remove the QREP block or update the content inside like I suggested but we cannot keep it like that.
